### ISSUE TITLE
Update log-config.yaml to log regtech library calls

### ISSUE THREAD

**Issue by jcadam14** [cfpb/regtech-user-fi-management#240]
We should add the following loggers to the log-config.yaml to log internal library calls:
```
  regtech_api_commons:
    level: INFO
    handlers:
      - default
    propagate: false
  regtech_user_fi_management:
    level: INFO
    handlers:
      - default
    propagate: false
```
